import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import { Header } from "./component/Header";
import { Footer } from "./component/Footer";

const manrope = Manrope({
  variable: "--font-monrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className}`} suppressHydrationWarning>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
